In [1]:
import numpy as np



In [10]:
A=np.random.random([3,3,3])
print A
B=A
print B
C=np.tensordot(A,B)

help(np.tensordot)

[[[ 0.49649214  0.73430399  0.34070076]
  [ 0.16707805  0.44530465  0.24437199]
  [ 0.62455959  0.94790574  0.42065059]]

 [[ 0.37471115  0.69664031  0.56035968]
  [ 0.18348478  0.13871484  0.65687326]
  [ 0.37767728  0.03077812  0.99163228]]

 [[ 0.27219695  0.71977896  0.23409949]
  [ 0.36043754  0.6961458   0.89115853]
  [ 0.01499001  0.33798582  0.0666748 ]]]
[[[ 0.49649214  0.73430399  0.34070076]
  [ 0.16707805  0.44530465  0.24437199]
  [ 0.62455959  0.94790574  0.42065059]]

 [[ 0.37471115  0.69664031  0.56035968]
  [ 0.18348478  0.13871484  0.65687326]
  [ 0.37767728  0.03077812  0.99163228]]

 [[ 0.27219695  0.71977896  0.23409949]
  [ 0.36043754  0.6961458   0.89115853]
  [ 0.01499001  0.33798582  0.0666748 ]]]
Help on function tensordot in module numpy.core.numeric:

tensordot(a, b, axes=2)
    Compute tensor dot product along specified axes for arrays >= 1-D.
    
    Given two tensors (arrays of dimension greater than or equal to one),
    `a` and `b`, and an array_like o

In [31]:
A=np.linspace(1,27,27).reshape(3,3,3)
B=np.linspace(1,27,27).reshape(3,3,3)
C=np.tensordot(A,B,axes=2)

#print A
#print "-"*20
#print B
print "-"*20
print C.shape
print C

--------------------
(3, 3)
[[  765.   810.   855.]
 [ 1818.  1944.  2070.]
 [ 2871.  3078.  3285.]]
